FROM archlinux:latest

RUN pacman -Syu --noconfirm git curl sudo zsh neovim
WORKDIR /dotfiles
COPY . /dotfiles
RUN git submodule update --init --recursive
RUN chmod +x ./setup-dotfiles.sh
RUN CI=1 ./setup-dotfiles.sh --reinit
CMD ["bash", "/dotfiles/test/test.sh"] 