FROM ubuntu:latest

RUN apt-get update && apt-get install -y git curl sudo locales zsh neovim
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
WORKDIR /dotfiles
COPY . /dotfiles
RUN git submodule update --init --recursive
RUN chmod +x ./bootstrap/setup-chezmoi.sh
RUN ./bootstrap/setup-chezmoi.sh --reinit
CMD ["bash", "/dotfiles/test/test.sh"] 