FROM alpine:latest

RUN apk add --no-cache git curl sudo zsh neovim bash
WORKDIR /dotfiles
COPY . /dotfiles
RUN git submodule update --init --recursive
RUN chmod +x ./bootstrap/setup-chezmoi.sh
RUN ./bootstrap/setup-chezmoi.sh --reinit
CMD ["bash", "/dotfiles/test/test.sh"] 