gui:
  # Background transparency enabled
  theme:
    lightTheme: false
    activeBorderColor:
      - "#58a6ff"
      - bold
    inactiveBorderColor:
      - "#444c56"
    optionsTextColor:
      - "#c9d1d9"
    selectedLineBgColor:
      - "#264f78"
    selectedRangeBgColor:
      - "#30363d" # GitHub selection background
    cherryPickedCommitBgColor:
      - "#bc8cff"
    cherryPickedCommitFgColor:
      - "#0d1117"
    unstagedChangesColor:
      - "#ff7b72"
    defaultFgColor:
      - "#c9d1d9" # GitHub foreground text
  
  # Enable mouse support
  mouseEvents: true
  
  # Border style for panels
  border: rounded
  
  # Show commit hash alongside tag/branch names in commits panel
  showCommandLog: true
  showBottomLine: true
  showFileTree: true
  showIcons: true
  
  # File tree style
  expandFocusedDir: true
  mainPanelSplitMode: flexible
  
  # Customize commit message view
  showRandomTip: false
  showCommandLog: true
  showBottomLine: true
  
  # Visibility
  showFileTree: true
  showListFooter: true
  showPanelJumps: true
  showBranchCommitHash: true
  
  # Enhanced UI elements
  experimentalShowBranchHeads: true
  branchColors:
    'main': '#3fb950'
    'master': '#3fb950'
    'develop': '#58a6ff'
    'release': '#bc8cff'
    'hotfix': '#ff7b72'
    'feature': '#d29922'
  authorColors:
    '*': '#c9d1d9' # Default author color
  portraitMode: "auto"
  nerdFontsVersion: "3"
  
  # Scrolling
  scrollHeight: 4
  scrollPastBottom: true
  
git:
  # Git settings for improved performance
  paging:
    colorArg: always
    useConfig: true
    pager: delta --dark --paging=never
  
  # Git merge settings
  merging:
    manualCommit: false
    args: "--no-ff"
  
  # Log settings
  log:
    order: "topo-order"
    showGraph: "always"
    showWholeGraph: true
  
  # Commit settings
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autofixForCommitMessages: true
  
  # Pull settings
  pull:
    mode: "rebase" # Use rebase mode by default for cleaner history
  
  # Skip untracked files during staging
  skipHookPrefix: WIP
  skipNoVerifyForCommit: "true"
  skipNoVerifyForPush: "true"
  
  # Prefer rebase over merge
  autoFetch: true
  autoRefresh: true
  
  # Branch name pattern
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"

# Custom command keybindings similar to GitHub
keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    scrollLeft: 'H'
    scrollRight: 'L'
    gotoTop: '<'
    gotoBottom: '>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextMatch: 'n'
    prevMatch: 'N'
    optionMenu: '?'
    select: '<space>'
    goInto: '<enter>'
    confirm: '<enter>'
    confirmInEditor: '<c-s>'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    executeCustomCommand: ':'
    createRebaseOptionsMenu: 'm'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: 'R'
    createPatchOptionsMenu: '<c-p>'
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: '<c-z>'
    filteringMenu: '<c-f>'
    diffingMenu: 'W'
    copyToClipboard: '<c-o>'
    submitEditorText: '<enter>'
    appendNewline: '<a-enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<c-w>'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
    
  status:
    checkForUpdate: 'u'
    recentRepos: '<c-r>'
    allBranchesLogGraph: 'a'
    
  files:
    commitChanges: 'c'
    commitChangesWithEditor: 'C'
    amendLastCommit: 'A'
    commitChangesWithoutHook: 'w'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
    
  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'
    pushTag: 'P'
    setUpstream: 'u'
    fetchRemote: 'f'
    
  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
    amendToCommit: 'A'
    pickCommit: 'p'
    revertCommit: 't'
    cherryPickCopy: 'c'
    cherryPickCopyRange: 'C'
    pasteCommits: 'v'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitAttributeToClipboard: 'y'
    
  stash:
    popStash: 'g'
    renameStash: 'r'
    
  commitFiles:
    checkoutCommitFile: 'c'
    
  main:
    toggleDragSelect: 'v'
    toggleDragSelect-alt: 'V'
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
    undo: 'z'
    
  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'

reporting: "on"
startupPopupVersion: 1
splashUpdatesIndex: 0
disableStartupPopups: true