[[mgr.prepend_keymap]]
on   = ["g", "r"]
run  = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Jump to the repo root"

[[mgr.prepend_keymap]]
on   = ["g", "c"]
run  = "cd ~/.config"
desc = "Jump to ~/.config"

[[mgr.prepend_keymap]]
on   = "<C-s>"
run  = 'shell "$SHELL" --block'
desc = "Shell here"
