[[verbs]]
invocation = "edit"
execution = "$EDITOR {file}"

[skin]
default_fg = "#c9d1d9"
default_bg = "#0d1117"
tree_fg = "#58a6ff"
selected_line_bg = "#264f78"
status_bar_fg = "#c9d1d9"
status_bar_bg = "#161b22" 